local config = {}

local default_config = {
  terminal_colors = true,
  styles = {
    comments = {},
    keywords = {},
    identifiers = {},
    functions = {},
    variables = {},
    booleans = {},
  },
  integrations = {
    -- alpha = true,
    -- cmp = true,
    -- flash = true,
    gitsigns = true,
    -- hop = false,
    -- indent_blankline = true,
    -- lazy = true,
    lsp = true,
    -- markdown = true,
    -- mason = true,
    -- mini = true,
    -- navic = false,
    -- neo_tree = false,
    -- neorg = false,
    -- noice = true,
    -- notify = true,
    rainbow_delimiters = true,
    telescope = true,
    treesitter = true,
    -- illuminate = true,
  },
  highlight_overrides = {},
}
